name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB_PACKAGE_PUBLICATION }}
      
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/zenoqwy/react-project-junia-thomas
          COMMIT_HASH=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_HASH
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_HASH
